// Code generated by "stringer -type=HubCommandType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INITIAL_REGISTER-0]
	_ = x[CL_ADDR_ADVERTISE-11]
	_ = x[CL_REGISTER-173]
	_ = x[CC_ZI_PLAYER_CONNECTED-53]
	_ = x[CC_REGISTER_PLAYER_LIST-54]
	_ = x[CC_PLAYER_ACK-55]
	_ = x[CC_GAMEPLAY_PROPS_UPDATE-56]
	_ = x[CL_CLIENT_CAPABILITYIES-57]
	_ = x[CC_HEARTBEAT-59]
	_ = x[CC_RANK_UPDATE-184]
	_ = x[CC_PROFILE_FIELD-185]
	_ = x[CC_PROFILE_BIT-186]
	_ = x[CC_INVENTORY_BIT-187]
	_ = x[CC_LOADOUT_UPDATE-188]
	_ = x[CC_ZONE_REGION_UPDATE-199]
	_ = x[CC_ZI_KICK_PLAYER_FROM_ZONES-203]
	_ = x[CC_DS_MULTIPLE_LOGIN-204]
	_ = x[CC_ZI_REMOVE_PLAYER-207]
	_ = x[CC_PLAYER_UPDATE-208]
	_ = x[CC_ZI_REGISTER_PLAYER-211]
	_ = x[CC_PROFILE_RELOAD-212]
	_ = x[CC_PLAYER_STATE_LIST-215]
	_ = x[CC_GAMEPLAY_RPC-216]
	_ = x[CC_PLAYER_DOCK_ACTION-217]
	_ = x[CC_PLAYER_DEPART-218]
	_ = x[CC_LOADOUT_UPDATE_5x-219]
	_ = x[CC_LOOT_CONFIG-242]
	_ = x[CC_GAMEPLAY_CONFIG-244]
	_ = x[CC_PLAYER_NOTIFICATION-248]
	_ = x[CC_PLAYER_REMOVED-251]
}

const _HubCommandType_name = "INITIAL_REGISTERCL_ADDR_ADVERTISECC_ZI_PLAYER_CONNECTEDCC_REGISTER_PLAYER_LISTCC_PLAYER_ACKCC_GAMEPLAY_PROPS_UPDATECL_CLIENT_CAPABILITYIESCC_HEARTBEATCL_REGISTERCC_RANK_UPDATECC_PROFILE_FIELDCC_PROFILE_BITCC_INVENTORY_BITCC_LOADOUT_UPDATECC_ZONE_REGION_UPDATECC_ZI_KICK_PLAYER_FROM_ZONESCC_DS_MULTIPLE_LOGINCC_ZI_REMOVE_PLAYERCC_PLAYER_UPDATECC_ZI_REGISTER_PLAYERCC_PROFILE_RELOADCC_PLAYER_STATE_LISTCC_GAMEPLAY_RPCCC_PLAYER_DOCK_ACTIONCC_PLAYER_DEPARTCC_LOADOUT_UPDATE_5xCC_LOOT_CONFIGCC_GAMEPLAY_CONFIGCC_PLAYER_NOTIFICATIONCC_PLAYER_REMOVED"

var _HubCommandType_map = map[HubCommandType]string{
	0:   _HubCommandType_name[0:16],
	11:  _HubCommandType_name[16:33],
	53:  _HubCommandType_name[33:55],
	54:  _HubCommandType_name[55:78],
	55:  _HubCommandType_name[78:91],
	56:  _HubCommandType_name[91:115],
	57:  _HubCommandType_name[115:138],
	59:  _HubCommandType_name[138:150],
	173: _HubCommandType_name[150:161],
	184: _HubCommandType_name[161:175],
	185: _HubCommandType_name[175:191],
	186: _HubCommandType_name[191:205],
	187: _HubCommandType_name[205:221],
	188: _HubCommandType_name[221:238],
	199: _HubCommandType_name[238:259],
	203: _HubCommandType_name[259:287],
	204: _HubCommandType_name[287:307],
	207: _HubCommandType_name[307:326],
	208: _HubCommandType_name[326:342],
	211: _HubCommandType_name[342:363],
	212: _HubCommandType_name[363:380],
	215: _HubCommandType_name[380:400],
	216: _HubCommandType_name[400:415],
	217: _HubCommandType_name[415:436],
	218: _HubCommandType_name[436:452],
	219: _HubCommandType_name[452:472],
	242: _HubCommandType_name[472:486],
	244: _HubCommandType_name[486:504],
	248: _HubCommandType_name[504:526],
	251: _HubCommandType_name[526:543],
}

func (i HubCommandType) String() string {
	if str, ok := _HubCommandType_map[i]; ok {
		return str
	}
	return "HubCommandType(" + strconv.FormatInt(int64(i), 10) + ")"
}
