//go:generate stringer -type=MessageType

package types

type MessageType uint16

const (
	SCMD_ASSIGNED_SHARD MessageType = iota
	SCMD_LB_QUEUE_INFO
	SCMD_LB_CVARS
	SCMD_AUTH_REQ
	CCMD_AUTH_REQUEST
	SCMD_AUTH_ACK
	SCMD_STEAM_NOT_ATTACHED
	SCMD_ARC_NOT_ATTACHED
	CCMD_STORE
	SCMD_STORE
	SCMD_STORE_SPOILED
	SCMD_CONNECT_DEDICATED_SERVER
	SCMD_GAME_ENDED
	CSCMD_ASYNC_REQ
	SCMD_NOTIFICATION
	SCMD_SQUAD_NOTIFICATION
	SCMD_SOCIAL_NOTIFICATION
	SCMD_TEACH_NOTIFICATION
	SCMD_CLAN_NOTIFICATION
	SCMD_USER_PROFILE_NOTIFICATION
	SCMD_QUEST_NOTIFICATION
	SCMD_LEAGUE_NOTIFICATION
	SCMD_VESSEL_NOTIFICATION
	SCMD_LOBBY_NOTIFICATION
	SCMD_KEEP_ALIVE
	SCMD_BAN_INFO
	SCMD_WELCOME_MSG
	SCMD_DOCK_SPACE_STATION
	SCMD_FREE_SPACE_DEBRIEFING
	SCMD_NEW_MOTD
	SCMD_TOURNAMENT_TEAMS_INFO
	SCMD_BRAWL_SCHEDULE
	SCMD_REWARD_SCHEDULE
	SCMD_PVE_SCHEDULE
	SCMD_LEAGUE_FORBIDDEN_EQUIPM
	SCMD_BATTLE_PASS_ACTIVATION
	SCMD_ZONES_WITH_DISABLED_QUE
	SCMD_ADVENTURE_NOTIFICATION
	SCMD_REPLACE_CHAT_MSG
)
