name: CI

permissions:
  contents: write

on: [ push, pull_request ]

jobs:
  build-shard:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: shard
            asset_name: shard_linux.zip
          - os: macos-latest
            artifact_name: shard
            asset_name: shard_macos.zip
          - os: windows-latest
            artifact_name: shard.exe
            asset_name: shard_win.zip

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - run: go build -o out/${{ matrix.artifact_name }} starconflict/cmd/shard
      - run: cp shard/config.json out/
        if: github.ref == 'refs/heads/master'
      - run: cp shard/cvars.json out/
        if: github.ref == 'refs/heads/master'
      - uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: ${{ matrix.asset_name }}
          path: out/
        if: github.ref == 'refs/heads/master'
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
        if: github.ref == 'refs/heads/master'
  build-loadbalancer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: loadbalancer
            asset_name: loadbalancer_linux.zip
          - os: macos-latest
            artifact_name: loadbalancer
            asset_name: loadbalancer_macos.zip
          - os: windows-latest
            artifact_name: loadbalancer.exe
            asset_name: loadbalancer_win.zip

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - run: go build -o out/${{ matrix.artifact_name }} starconflict/cmd/loadbalancer
      - uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: ${{ matrix.asset_name }}
          path: out/
        if: github.ref == 'refs/heads/master'
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
        if: github.ref == 'refs/heads/master'
  build-tools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: tools
            asset_name: tools_linux.zip
          - os: macos-latest
            artifact_name: tools
            asset_name: tools_macos.zip
          - os: windows-latest
            artifact_name: tools.exe
            asset_name: tools_win.zip

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - run: go build -o out/${{ matrix.artifact_name }} starconflict/cmd/tools
      - uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: ${{ matrix.asset_name }}
          path: out/
        if: github.ref == 'refs/heads/master'
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
        if: github.ref == 'refs/heads/master'
